### ISSUE TITLE
Syntax highlighting in Helix

### ISSUE THREAD

**Issue by biskwikman** [bscan/RakuNavigator#22]
I've gotten errors to appear but I can't get syntax highlighting to work in Helix. Is there something I'm missing in my languages.toml?

```toml
[language-server.rakunavigator]
command = "node"
args = ["/home/dan/Programs/RakuNavigator/server/out/server.js", "--stdio"]

[[language]]
name = "raku"
scope = "source.raku"
file-types = ["raku", "rakudoc"]
comment-tokens = "#"
language-servers = ["rakunavigator"]
```
